In [418]:
import pandas as pd
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')

from statsmodels.tsa.arima_model import ARIMA
import matplotlib.pyplot as plt
from pandas.plotting import autocorrelation_plot
from sklearn.metrics import mean_squared_error

import plotly.graph_objects as go

import numpy as np


In [436]:
def to_int(value):
    try:
        n = value.strip()
        n = n.replace(",",'')
        return int(n)
    except:
        return value
    
def to_pct(value):
    try:
        n = value.replace("%",'')
        return float(n)
    except:
        return value
    
    
def to_date(value):
    return pd.to_datetime(value)

def predictions(column):
    column = column.dropna()
    data = column.values
    model = ARIMA(data, order=(1, 1, 1))
    model_fit = model.fit(disp=False)
    yhat = model_fit.predict(len(data),len(data)+3, typ='levels')
    return yhat

In [437]:
nat_header = ['MAP Region',
 'Year',
 'Quarter',
 'Properties',
 'Units',
 'Average Occupancy',
 'Median Occupancy',
 'Annual Absorption',
 'Annual Inventory Growth',
 'Properties Under Construction',
 'Units Under Construction',
 'Construction vs. Inventory',
 'Average Rent',
 'Annual Rent Growth',
 'Units Started',
 'Rolling 4-Quarter Units Started',
 'Rolling 4-Quarter Starts vs. Inventory']

In [438]:
df = pd.read_csv('data/national.csv', names = nat_header, header = 0)

In [439]:
drop = ['MAP Region','Year']
df = df.drop(drop,axis = 1)

In [440]:
df.Quarter = df.Quarter.apply(lambda x: to_date(x))
df.Properties = df.Properties.apply(lambda x:to_int(x))
df.Units = df.Units.apply(lambda x: to_int(x))
df['Average Occupancy'] = df['Average Occupancy'].apply(lambda x: to_pct(x))
df['Median Occupancy'] = df['Median Occupancy'].apply(lambda x: to_pct(x))
df['Annual Absorption'] = df['Annual Absorption'].apply(lambda x: to_pct(x))
df['Annual Inventory Growth'] = df['Annual Inventory Growth'].apply(lambda x: to_pct(x))
df['Properties Under Construction'] = df['Properties Under Construction'].apply(lambda x: to_int(x))
df['Units Under Construction'] = df['Units Under Construction'].apply(lambda x: to_int(x))
df['Construction vs. Inventory'] = df['Construction vs. Inventory'].apply(lambda x: to_pct(x))
df['Average Rent'] = df['Average Rent'].apply(lambda x: to_int(x))
df['Annual Rent Growth'] = df['Annual Rent Growth'].apply(lambda x: to_pct(x))
df['Units Started'] = df['Units Started'].apply(lambda x: to_int(x))
df['Rolling 4-Quarter Units Started'] = df['Rolling 4-Quarter Units Started'].apply(lambda x: to_int(x))
df['Rolling 4-Quarter Starts vs. Inventory'] = df['Rolling 4-Quarter Starts vs. Inventory'].apply(lambda x: to_pct(x))

## Add in Predictions

In [441]:
future = ['3Q2019','4Q2019','1Q2020','2Q2020']
future = [to_date(x) for x in future]

In [442]:
cols = df.columns.to_list()
cols = cols[1:]

In [443]:
df['Rolling 4-Quarter Units Started'][2]

nan

In [444]:
df

Quarter  Properties   Units  Average Occupancy  Median Occupancy  \
0  2005-10-01        3672  459477               91.3              94.6   
1  2006-01-01        3703  464518               91.0              94.6   
2  2006-04-01        3717  466392               91.4              94.8   
3  2006-07-01        3734  468860               91.3              94.6   
4  2006-10-01        3745  470864               91.3              94.8   
5  2007-01-01        3769  474182               91.3              94.9   
6  2007-04-01        3779  476834               90.9              94.3   
7  2007-07-01        3790  478994               90.8              94.2   
8  2007-10-01        3810  482533               90.5              93.8   
9  2008-01-01        3835  487343               89.8              93.0   
10 2008-04-01        3853  490458               89.3              92.5   
11 2008-07-01        3872  492932               89.0              92.2   
12 2008-10-01        3887  496246               88.4              91.8   
13 2009-01-01        3913  499279               87.7              91.2   
14 2009-04-01        3943  504310               87.0              90.7   
15 2009-07-01        3957  506842               87.3              90.9   
16 2009-10-01        3970  508710               87.2              90.8   
17 2010-01-01        3981  511085               86.9              90.5   
18 2010-04-01        3993  512982               87.1              90.8   
19 2010-07-01        4008  515154               87.2              90.9   
20 2010-10-01        4014  516659               87.4              91.2   
21 2011-01-01        4029  518363               87.5              91.1   
22 2011-04-01        4039  519603               87.6              91.2   
23 2011-07-01        4053  521089               87.9              91.5   
24 2011-10-01        4069  523631               88.0              91.8   
25 2012-01-01        4083  525317               88.2              91.7   
26 2012-04-01        4096  526878               88.5              92.1   
27 2012-07-01        4115  528763               88.7              92.4   
28 2012-10-01        4136  530842               89.0              92.4   
29 2013-01-01        4155  532869               88.9              92.3   
30 2013-04-01        4167  534922               88.8              92.1   
31 2013-07-01        4188  536528               89.2              92.8   
32 2013-10-01        4211  539595               89.5              93.2   
33 2014-01-01        4233  541818               89.5              93.0   
34 2014-04-01        4258  544342               89.7              93.2   
35 2014-07-01        4284  547028               90.0              93.7   
36 2014-10-01        4310  549596               90.2              93.7   
37 2015-01-01        4341  552648               89.7              93.2   
38 2015-04-01        4380  557218               89.5              93.0   
39 2015-07-01        4405  560393               89.7              93.3   
40 2015-10-01        4440  563615               90.0              93.5   
41 2016-01-01        4467  567206               89.8              93.1   
42 2016-04-01        4495  570328               89.5              92.9   
43 2016-07-01        4530  575320               89.5              92.9   
44 2016-10-01        4572  581373               89.4              93.1   
45 2017-01-01        4608  585328               89.1              92.6   
46 2017-04-01        4651  590558               88.6              92.0   
47 2017-07-01        4688  594747               88.6              92.2   
48 2017-10-01        4728  599652               88.6              92.3   
49 2018-01-01        4765  604185               88.2              91.5   
50 2018-04-01        4806  610263               87.9              91.4   
51 2018-07-01        4839  615455               87.8              91.9   
52 2018-10-01        4879  620984               87.9              92.0   
53 2019-01

In [447]:
for each in cols:
    
    p = predictions(df[each])
    
    f = pd.DataFrame(future, columns = ['Quarter'])
    f['Predicted'] = p
    print(p)
    
    fig = go.Figure()
    fig.add_trace(go.Scatter(x = df.Quarter, y = df[each],
                        mode = 'lines',
                        name = 'Historical'))
    
    fig.add_trace(go.Scatter(x = f.Quarter, y = f.Predicted,
                        mode = 'lines',
                        name = 'Predicted'))
    
    fig.update_layout(
        title = {
            'text': "{} vs Time".format(each),
            'y':0.95,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top',
        },
        xaxis_title = "Time",
        yaxis_title = each,
    )
    fig.show()
    fig.write_image("{} vs Time.png".format(each))

[5014.63306769 5047.94212541 5080.94032762 5113.64029472]


[637773.81948794 642066.58859602 646308.47379644 650502.45605768]


[88.23057486 88.09990962 88.05751286 87.99354783]


[91.96204383 91.88094986 91.84190886 91.79051297]


[3.00859731 3.01964109 3.02926485 3.03971284]


[2.8032956  2.87417345 2.83734679 2.86974144]


[344.99972868 341.18009245 340.78589788 342.02577196]


[42008.31002772 41543.10666228 41196.73551218 40949.46908298]


[6.56857477 6.46530805 6.38483822 6.32282455]


[4225.29391109 4250.69009971 4276.11257847 4301.54181504]


[2.60872579 2.55860387 2.52580095 2.50028678]


[4166.69990689 4220.58871483 4242.09308213 4262.50478443]


[16848.40055942 16120.63254649 15635.38615411 15315.43358306]


[2.62033656 2.49768657 2.41310612 2.35394583]
